title: Paul Roub - Links
subheads:
    - "Places you might want to go if we met at a gig"

email: paul@paulroub.com
description: >-
    Places you might want to go if we met at a gig
baseurl: ""
url: "https://links.paulroub.com/"

# uncomment and fill in any social IDs you want linked from the top of your page

# email: "email@example.com"
# telephone_number: "999-999-9999"
# bluesky_username: "my_bluesky_username"
# cashapp_username: "my_cashapp_username"
# discord_username: "my_discord_username"
# github_username: "my_github_username"
instagram_username: "paulroub"
# mastodon_username: "@username@example.host"
# pinterest_username: "my_pinterest_username"
# threads_username: "my_threads_username"
# tiktok_username: "my_tiktok_username"
facebook_username: "paulroubmusic"
# venmo_username: "my_venmo_username"
# youtube_username: "my_youtube_username"

# uncomment for plausible.io analytics, should match the "url" above
# plausible_io: example.com

# uncomment to add your google analytics
# google_analytics: UA-NNNNNNNN-N

# Build settings
theme: jekyll-theme-linky
plugins:
    - jekyll-feed

github_username: false

exclude:
    - VERSION
    - bin
    - linky.gemspec
    - netlify.toml
    - scripts

linky:
    body_background: "#f0cc98"
    body_foreground: "#333"
    button_background: "#fff"
    button_foreground: "#333"
    social_button_color: "#333"

collections:
    - links

# tell the jekyll-feed plugin to include the links collection
feed:
    collections:
        - links
